# Generated by Django 4.2.17 on 2025-01-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.accesshistory',),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.info',),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.users',),
        ),
    ]
