# Generated by Django 4.2.17 on 2025-01-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_airquality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirQuality',
        ),
    ]
